<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="9" hostname="Rajesh" failures="4" tests="49" name="Default test" time="855.335" errors="0" timestamp="2024-07-08T11:08:08 IST">
  <testcase classname="Testcases.Post_login" name="Login_Dashboard" time="12.599"/>
  <testcase classname="Testcases.Post_login" name="signup_login" time="12.349"/>
  <testcase classname="Testcases.Post_login" name="after_login_changeto_filter" time="15.387"/>
  <testcase classname="Testcases.Post_login" name="Surveycard_back_navigation" time="17.827"/>
  <testcase classname="Testcases.Post_login" name="printing_survey_title" time="11.609"/>
  <testcase classname="Testcases.Post_login" name="allsurveys_cardLIST" time="11.614"/>
  <testcase classname="Testcases.Post_login" name="Scheduled_surveys_cardNumber" time="15.326"/>
  <testcase classname="Testcases.Post_login" name="Completed_survey_list" time="15.245"/>
  <testcase classname="Testcases.Post_login" name="LIVE_surveycard_Numbers" time="15.38"/>
  <testcase classname="Testcases.Post_login" name="Overview" time="13.183"/>
  <testcase classname="Testcases.Post_login" name="allsurveys_Heading" time="12.212"/>
  <testcase classname="Testcases.Post_login" name="print_the_firstsurvey_response" time="37.294">
    <skipped/>
  </testcase> <!-- print_the_firstsurvey_response -->
  <testcase classname="Testcases.Post_login" name="print_the_firstsurvey_response" time="37.254">
    <failure type="java.lang.AssertionError" message="No survey questions found expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: No survey questions found expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertFalse(Assert.java:78)
at Testcases.Post_login.print_the_firstsurvey_response(Post_login.java:285)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- print_the_firstsurvey_response -->
  <testcase classname="Testcases.Post_login" name="change_filters" time="20.743"/>
  <testcase classname="Testcases.Post_login" name="login_switch_home" time="20.635"/>
  <testcase classname="Testcases.Post_login" name="getstarted_login" time="26.17"/>
  <testcase classname="Testcases.Post_login" name="verifySignupNotDisplayedAfterNavigation" time="18.572">
    <skipped/>
  </testcase> <!-- verifySignupNotDisplayedAfterNavigation -->
  <testcase classname="Testcases.Post_login" name="verifySignupNotDisplayedAfterNavigation" time="18.55">
    <failure type="java.lang.AssertionError" message="Signup screen is still displayed after navigating back expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: Signup screen is still displayed after navigating back expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertFalse(Assert.java:78)
at Testcases.Post_login.verifySignupNotDisplayedAfterNavigation(Post_login.java:424)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- verifySignupNotDisplayedAfterNavigation -->
  <testcase classname="Testcases.Post_login" name="Delete_cookies" time="14.671"/>
  <testcase classname="Testcases.SignUp" name="click_actions" time="2.255"/>
  <testcase classname="Testcases.SignUp" name="clickon_signup" time="1.699"/>
  <testcase classname="Testcases.SignUp" name="login_signup" time="1.701"/>
  <testcase classname="Testcases.SignUp" name="signup_Invalidemail" time="26.477"/>
  <testcase classname="Testcases.SignUp" name="signup_Invalid_OTP" time="32.034"/>
  <testcase classname="Testcases.SignUp" name="Login_signup" time="1.33">
    <skipped/>
  </testcase> <!-- Login_signup -->
  <testcase classname="Testcases.SignUp" name="Login_signup" time="1.262">
    <failure type="org.openqa.selenium.StaleElementReferenceException" message="stale element reference: stale element not found in the current frame
  (Session info: chrome=126.0.6478.127)
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: &amp;apos;3.141.59&amp;apos;, revision: &amp;apos;e82be7d358&amp;apos;, time: &amp;apos;2018-11-14T08:25:53&amp;apos;
System info: host: &amp;apos;RAJESH&amp;apos;, ip: &amp;apos;192.168.0.232&amp;apos;, os.name: &amp;apos;Windows 11&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;17.0.11&amp;apos;
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 126.0.6478.127, chrome: {chromedriverVersion: 126.0.6478.126 (d36ace6122e..., userDataDir: C:\Users\Rajes\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:55516}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 869600484705051a5090f0d8b8e5065a">
      <![CDATA[org.openqa.selenium.StaleElementReferenceException: stale element reference: stale element not found in the current frame
  (Session info: chrome=126.0.6478.127)
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'RAJESH', ip: '192.168.0.232', os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.11'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 126.0.6478.127, chrome: {chromedriverVersion: 126.0.6478.126 (d36ace6122e..., userDataDir: C:\Users\Rajes\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:55516}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 869600484705051a5090f0d8b8e5065a
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:285)
at org.openqa.selenium.remote.RemoteWebElement.sendKeys(RemoteWebElement.java:106)
at Testcases.SignUp.Login_signup(SignUp.java:157)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- Login_signup -->
  <testcase classname="Testcases.SignUp" name="existing_emailid" time="3.342"/>
  <testcase classname="Testcases.SignUp" name="signup_resendcode" time="36.527"/>
  <testcase classname="Testcases.SignUp" name="signup_MultipleInvalidOtps" time="42.884"/>
  <testcase classname="Testcases.Login_in" name="clickon_login" time="13.888"/>
  <testcase classname="Testcases.Login_in" name="Resend_OTP" time="51.201"/>
  <testcase classname="Testcases.Login_in" name="Invalid_Email" time="10.942"/>
  <testcase classname="Testcases.Login_in" name="email_error_message" time="11.021"/>
  <testcase classname="Testcases.Login_in" name="OTP_error" time="15.73"/>
  <testcase classname="Testcases.Login_in" name="login_signup" time="1.701"/>
  <testcase classname="Testcases.Login_in" name="New_emailid" time="11.13"/>
  <testcase classname="Testcases.Login_in" name="signup_login" time="12.257"/>
  <testcase classname="Testcases.Login_in" name="New_emailid_clickon_get_started" time="10.988"/>
  <testcase classname="Testcases.Login_in" name="New_emailidclickon_get_started" time="11.085"/>
  <testcase classname="Testcases.clickable_function" name="TC_01" time="1.626"/>
  <testcase classname="Testcases.clickable_function" name="TC_02" time="1.61"/>
  <testcase classname="Testcases.clickable_function" name="TC_03" time="5.526"/>
  <testcase classname="Testcases.clickable_function" name="TC_05" time="7.1"/>
  <testcase classname="Testcases.clickable_function" name="TC_06" time="6.02"/>
  <testcase classname="Testcases.clickable_function" name="TC_07" time="9.555"/>
  <testcase classname="Testcases.clickable_function" name="TC_08" time="9.369"/>
  <testcase classname="Testcases.clickable_function" name="TC_09" time="23.86">
    <skipped/>
  </testcase> <!-- TC_09 -->
  <testcase classname="Testcases.clickable_function" name="TC_09" time="23.818">
    <failure type="java.lang.AssertionError" message="No blog elements found expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: No blog elements found expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertTrue(Assert.java:56)
at Testcases.clickable_function.TC_09(clickable_function.java:230)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- TC_09 -->
  <testcase classname="Testcases.clickable_function" name="TC_10" time="4.261"/>
  <testcase classname="Testcases.clickable_function" name="TC_04" time="0.0">
    <ignored/>
  </testcase> <!-- TC_04 -->
  <testcase classname="Testcases.SignUp" name="signup_Welcome" time="0.0">
    <ignored/>
  </testcase> <!-- signup_Welcome -->
  <testcase classname="Baseclass.Basetest" name="@BeforeSuite setupExtentReports" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setupExtentReports -->
  <testcase classname="Baseclass.Basetest" name="@AfterSuite tearDownExtentReports" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDownExtentReports -->
  <testcase classname="Baseclass.Basetest" name="@AfterSuite tearDownExtentReports" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDownExtentReports -->
  <testcase classname="Baseclass.Basetest" name="@BeforeSuite setupExtentReports" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setupExtentReports -->
  <testcase classname="Baseclass.Basetest" name="@AfterSuite tearDownExtentReports" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDownExtentReports -->
  <testcase classname="Baseclass.Basetest" name="@BeforeSuite setupExtentReports" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setupExtentReports -->
  <testcase classname="Testcases.SignUp" name="signup_EmptyEmail" time="0.0">
    <ignored/>
  </testcase> <!-- signup_EmptyEmail -->
</testsuite> <!-- Default test -->
