<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Rajesh" failures="1" tests="11" name="Testcases.clickable_function" time="111.406" errors="0" timestamp="2024-07-08T11:08:10 IST" skipped="2">
  <testcase classname="Testcases.clickable_function" name="TC_01" time="3.401"/>
  <system-out/>
  <testcase classname="Testcases.clickable_function" name="TC_02" time="3.275"/>
  <system-out/>
  <testcase classname="Testcases.clickable_function" name="TC_03" time="7.214"/>
  <system-out/>
  <testcase classname="Testcases.clickable_function" name="TC_05" time="9.485"/>
  <system-out/>
  <testcase classname="Testcases.clickable_function" name="TC_06" time="7.784"/>
  <system-out/>
  <testcase classname="Testcases.clickable_function" name="TC_07" time="12.215"/>
  <system-out/>
  <testcase classname="Testcases.clickable_function" name="TC_08" time="11.075"/>
  <system-out/>
  <testcase classname="Testcases.clickable_function" name="TC_09" time="25.522">
    <failure message="No blog elements found expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: No blog elements found expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertTrue(Assert.java:56)
at Testcases.clickable_function.TC_09(clickable_function.java:230)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- TC_09 -->
  <system-out/>
  <testcase classname="Testcases.clickable_function" name="TC_09" time="25.499">
    <skipped/>
  </testcase> <!-- TC_09 -->
  <system-out/>
  <testcase classname="Testcases.clickable_function" name="TC_10" time="5.936"/>
  <system-out/>
  <testcase classname="Testcases.clickable_function" name="TC_04">
    <skipped/>
  </testcase> <!-- TC_04 -->
  <system-out/>
</testsuite> <!-- Testcases.clickable_function -->
