<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Rajesh" failures="2" tests="19" name="Testcases.Post_login" time="391.561" errors="0" timestamp="2024-07-08T11:08:10 IST" skipped="2">
  <testcase classname="Testcases.Post_login" name="Login_Dashboard" time="17.031"/>
  <system-out/>
  <testcase classname="Testcases.Post_login" name="signup_login" time="14.226"/>
  <system-out/>
  <testcase classname="Testcases.Post_login" name="after_login_changeto_filter" time="17.287"/>
  <system-out/>
  <testcase classname="Testcases.Post_login" name="Surveycard_back_navigation" time="20.894"/>
  <system-out/>
  <testcase classname="Testcases.Post_login" name="printing_survey_title" time="14.264"/>
  <system-out/>
  <testcase classname="Testcases.Post_login" name="allsurveys_cardLIST" time="13.402"/>
  <system-out/>
  <testcase classname="Testcases.Post_login" name="Scheduled_surveys_cardNumber" time="17.183"/>
  <system-out/>
  <testcase classname="Testcases.Post_login" name="Completed_survey_list" time="17.509"/>
  <system-out/>
  <testcase classname="Testcases.Post_login" name="LIVE_surveycard_Numbers" time="17.553"/>
  <system-out/>
  <testcase classname="Testcases.Post_login" name="Overview" time="16.850"/>
  <system-out/>
  <testcase classname="Testcases.Post_login" name="allsurveys_Heading" time="16.042"/>
  <system-out/>
  <testcase classname="Testcases.Post_login" name="print_the_firstsurvey_response" time="39.107">
    <failure message="No survey questions found expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: No survey questions found expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertFalse(Assert.java:78)
at Testcases.Post_login.print_the_firstsurvey_response(Post_login.java:285)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- print_the_firstsurvey_response -->
  <system-out/>
  <testcase classname="Testcases.Post_login" name="print_the_firstsurvey_response" time="39.013">
    <skipped/>
  </testcase> <!-- print_the_firstsurvey_response -->
  <system-out/>
  <testcase classname="Testcases.Post_login" name="change_filters" time="22.443"/>
  <system-out/>
  <testcase classname="Testcases.Post_login" name="login_switch_home" time="22.479"/>
  <system-out/>
  <testcase classname="Testcases.Post_login" name="getstarted_login" time="28.070"/>
  <system-out/>
  <testcase classname="Testcases.Post_login" name="verifySignupNotDisplayedAfterNavigation" time="20.303">
    <skipped/>
  </testcase> <!-- verifySignupNotDisplayedAfterNavigation -->
  <system-out/>
  <testcase classname="Testcases.Post_login" name="verifySignupNotDisplayedAfterNavigation" time="21.153">
    <failure message="Signup screen is still displayed after navigating back expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Signup screen is still displayed after navigating back expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertFalse(Assert.java:78)
at Testcases.Post_login.verifySignupNotDisplayedAfterNavigation(Post_login.java:424)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- verifySignupNotDisplayedAfterNavigation -->
  <system-out/>
  <testcase classname="Testcases.Post_login" name="Delete_cookies" time="16.752"/>
  <system-out/>
</testsuite> <!-- Testcases.Post_login -->
